SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


DROP TABLE IF EXISTS `partiesproposees`;
CREATE TABLE IF NOT EXISTS `partiesproposees` (
  `gidp` int(5) NOT NULL AUTO_INCREMENT,
  `prospect` int(4) DEFAULT NULL,
  `origine` int(4) NOT NULL,
  `macouleur` char(1) DEFAULT NULL,
  `cadence` int(2) NOT NULL,
  `reserve` int(2) NOT NULL,
  `commentaire` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`gidp`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
